apiVersion: v1
kind: Service
metadata:
  name: serviceforstatefulset
  namespace: default
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: nginx-web
