---
kind: Service
apiVersion: v1
metadata:
  name: serviceforstatefulset
spec:
  selector:
    app: nginx
  ports:
  # Default port used by the image
  - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marc-statefulset-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/ss"
        backend:
          service:
            name: serviceforstatefulset
            port:
              number: 80
---
