---
apiVersion: v1
kind: Service
metadata:
  name: serviceforstatefulset
  namespace: default
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
~
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marc-statefulset-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/ss"
        backend:
          service:
            name: serviceforstatefulset
            port:
              number: 80
---
